name: Gradle CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:

  build:

    name: Gradle-Build
    
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4
        
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      
      - name: CI
        uses: actions/upload-artifact@v3
        with: 
          name: snapshot
          path: build/libs/*.jar